# Generated by Django 5.2.9 on 2025-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
