# Generated by Django 5.2.12 on 2026-08-01 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0005_remove_product_image_url_review_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
