# Generated by Django 5.2.12 on 2026-08-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0007_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
